{
 "title": "Network Latency Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Epoch Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "XRAN Epoch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"epoch\" FROM xranicmp..latency WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UE Epoch",
     "query": "SELECT \"epoch\" FROM ueicmp..latency WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Waterspout Epoch",
     "query": "SELECT \"epoch\" FROM waterspouticmp..latency WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Cloudlet Epoch",
     "query": "SELECT \"epoch\" FROM cloudleticmp..latency WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "UE Epoch Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "UE Epoch",
     "query": "SELECT \"epoch\" FROM ueicmp..latency WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Waterspout Epoch Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "Waterspout Epoch",
     "query": "SELECT \"epoch\" FROM waterspouticmp..latency WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Cloudlet Epoch Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Cloudlet Epoch",
     "query": "SELECT \"epoch\" FROM cloudleticmp..latency WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "XRAN Epoch Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "alias": "XRAN Epoch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"epoch\" FROM xranicmp..latency WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node Sequences",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \"sequence\",\"epoch\" AS \"WS-EP\" FROM waterspouticmp..latency WHERE $timeFilter fill(null)"
    },
    {
     "alias": "$col",
     "query": "SELECT \"sequence\" ,\"epoch\" AS \"CL-EP\" FROM cloudleticmp..latency WHERE $timeFilter fill(null)"
    },
    {
     "alias": "$col",
     "query": "SELECT \"sequence\",\"epoch\" AS \"UE-EP\" FROM ueicmp..latency WHERE $timeFilter fill(null)"
    },
    {
     "alias": "$col",
     "query": "SELECT \"sequence\",\"epoch\" AS \"XR-EP\" FROM xranicmp..latency WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Adjusted UE-XRAN Segment Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "UE-XRAN Uplink",
     "query": "SELECT median(\"ue_xran_adjust\")*1000 FROM \"uplink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "UE-XRAN Downlink",
     "query": "SELECT median(\"ue_xran_adjust\")*1000 FROM \"downlink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Other Metrics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Round Trip Time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"rtt\")*1000 FROM \"downlink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "App Processing (ms)",
     "query": "SELECT median(\"cloudlet_proc\")*1000 FROM \"downlink\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Measurement Count",
     "query": "SELECT count(\"rtt\") FROM \"downlink\" WHERE $timeFilter fill(null)"
    }
   ]
  }
 ]
}