{
 "title": "Network Latency Segmentation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UE-XRAN Segment Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"ue_xran\")*1000 FROM \"uplink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"ue_xran\")*1000 FROM \"downlink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XRAN-EPC Segment Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"xran_epc\") FROM \"uplink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT median(\"xran_epc\") FROM \"downlink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "EPC-Cloudlet Segment Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"epc_cloudlet\") FROM \"uplink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"epc_cloudlet\") FROM \"downlink\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE to XRAN Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UE to XRAN ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"ue_xran\")*1000, min(\"ue_xran\")*1000, max(\"ue_xran\")*1000, mean(\"ue_xran\")*1000,stddev(\"ue_xran\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XRAN to EPC Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "XRAN to EPC ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"xran_epc\")*1000, min(\"xran_epc\")*1000, max(\"xran_epc\")*1000, mean(\"xran_epc\")*1000,stddev(\"xran_epc\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EPC to Cloudlet Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "EPC to Cloudlet ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"epc_cloudlet\")*1000, min(\"epc_cloudlet\")*1000, max(\"epc_cloudlet\")*1000, mean(\"epc_cloudlet\")*1000, stddev(\"epc_cloudlet\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XRAN to UE Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "XRAN to UE ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"ue_xran\")*1000, min(\"ue_xran\")*1000, max(\"ue_xran\")*1000, mean(\"ue_xran\")*1000,stddev(\"ue_xran\")*1000  FROM \"downlink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EPC to XRAN Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "EPC to XRAN ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"xran_epc\")*1000, min(\"xran_epc\")*1000, max(\"xran_epc\")*1000, mean(\"xran_epc\")*1000,stddev(\"xran_epc\")*1000 FROM \"downlink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloudlet to EPC Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cloudlet to EPC ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"epc_cloudlet\")*1000, min(\"epc_cloudlet\")*1000, max(\"epc_cloudlet\")*1000, mean(\"epc_cloudlet\")*1000,stddev(\"epc_cloudlet\")*1000  FROM \"downlink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Adjusted UE-XRAN (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offset ($col)",
     "query": "SELECT median(\"offset\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)\n"
    },
    {
     "alias": "Raw Uplink ($col)",
     "query": "SELECT median(\"ue_xran\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Adusted Uplink ($col)",
     "query": "SELECT median(\"ue_xran_adjust\")*1000 FROM \"uplink\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Raw Downlink ($col)",
     "query": "SELECT median(\"ue_xran\")*1000 FROM \"downlink\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Adusted Downlink ($col)",
     "query": "SELECT median(\"ue_xran_adjust\")*1000,count(\"ue_xran_adjust\") FROM \"downlink\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "UE NTP Offset (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"offset\")*1000 FROM winoffset.autogen.winoffset WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Round Trip Times (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RTT ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"rtt\")*1000, min(\"rtt\")*1000, max(\"rtt\")*1000, mean(\"rtt\")*1000,stddev(\"rtt\")*1000 FROM \"downlink\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Adjusted UE-XRAN Latency (ms)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT \"ue_xran_adjust\"*1000 FROM \"uplink\" WHERE $timeFilter fill(null)"
    },
    {
     "query": "SELECT \"ue_xran_adjust\"*1000 FROM \"downlink\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "UE NTP Offset (us)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 27 },
   "targets": [
    {
     "query": "SELECT \"offset\"*1000000 FROM winoffset.autogen.winoffset WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "UE NTP Offset (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offset ($col)",
     "query": "SELECT median(\"offset\")*1000, min(\"offset\")*1000, max(\"offset\")*1000, mean(\"offset\")*1000,stddev(\"offset\")*1000,count(\"offset\") FROM winoffset.autogen.winoffset WHERE $timeFilter fill(null)"
    }
   ]
  }
 ]
}