{
 "title": "Network Latency Segmentation Summary",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uplink Median Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UE to XRAN (adj)",
     "query": "SELECT median(\"ue_xran_adjust\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "XRAN to EPC",
     "query": "SELECT median(\"xran_epc\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "EPC to Cloudlet",
     "query": "SELECT median(\"epc_cloudlet\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Downlink Median Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cloudlet to EPC",
     "query": "SELECT median(\"cloudlet_epc\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "EPC to XRAN",
     "query": "SELECT median(\"epc_xran\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "UE to XRAN (adj)",
     "query": "SELECT median(\"xran_ue_adjust\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Other Metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Round Trip Time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"rtt\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Measurement Count",
     "query": "SELECT count(\"rtt\") FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Uplink Latency Std Dev (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UE to XRAN (adj)",
     "query": "SELECT stddev(\"ue_xran_adjust\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "XRAN to EPC",
     "query": "SELECT stddev(\"xran_epc\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "EPC to Cloudlet",
     "query": "SELECT stddev(\"epc_cloudlet\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Downlink Latency Std Dev (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cloudlet to EPC",
     "query": "SELECT stddev(\"cloudlet_epc\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "EPC to XRAN",
     "query": "SELECT stddev(\"epc_xran\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "XRAN to UE (adj)",
     "query": "SELECT stddev(\"xran_ue_adjust\")*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "XRAN-EPC Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "XRAN to EPC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"xran_epc\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "EPC to XRAN",
     "query": "SELECT median(\"epc_xran\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UE-XRAN Latency Adjusted (ms)",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "UE To XRAN",
     "query": "SELECT \"ue_xran_adjust\"*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "XRAN To UE",
     "query": "SELECT \"xran_ue_adjust\"*1000 FROM \"segments\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "UE-XRAN Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "alias": "UE to XRAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"ue_xran\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "XRAN to UE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"xran_ue\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EPC-Cloudlet Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "alias": "EPC to Cloudlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"epc_cloudlet\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cloudlet to EPC",
     "query": "SELECT median(\"cloudlet_epc\")*1000 FROM \"segments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UE NTP Offset (us)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"offset\")*1000000 FROM winoffset.DefaultRetentionPolicy.winoffset WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}